### ISSUE TITLE
Decide Java Version

### ISSUE THREAD

**Issue by vcaldas** [vcaldas/iSBatch#10]
ImageJ rungs by default on Java 1.6. 
Asking users to upgrade will for sure decrease the reach of the code. We may want to to make it on Java 1.6.
I think that no much code may be changed

**Comment by cmpunter** [comment]
It depends, I always use ImageJ without the bundled JVM. In that case you can use any version of the JVM (any version above 1.6 that is ;). I agree that we stick to 1.6 since some people will use the bundled JVM. We don't really need features of JVM 1.7/1.8 anyway.
