### ISSUE TITLE
save and save as menu option.

### ISSUE THREAD

**Issue by vcaldas** [vcaldas/iSBatch#13]
Allow user to save current state of database or save somewhere else.

The option save as won't movie the files along for now. 
Sure if file don't have know location, the code as where to save it initially.

**Comment by cmpunter** [comment]
Save and save as is essentially the save functionality. You cannot save an existing database under a different name. This would involve creating a new database file (easy) but also copying all created files to a new folder (difficult, when dealing with a lot of files)
