### ISSUE TITLE
preferences 

### ISSUE THREAD

**Issue by vcaldas** [vcaldas/iSBatch#15]
This works in a hierarchical way and serves as a support for analysis.
For now, a placeholder is needed and fields will be added as required.

Works on E S F.

a table preferences should be created in the database. Primary key relates do node ID.

Pixel size   nm per pixel. Default is 100nm

scale bar size 1um

Btw, a gui should pop up with all fields to be altered. User has no power to add more fields. Every colum I  the database is one field.

**Comment by cmpunter** [comment]
A lot of the preferences (or properties) can directly be stored as properties in the individual nodes (experiment, sample, field of view, file) by using setProperty and getProperty. The properties are saved in the database (don't forget to save the database ;)),
I think preferences should be for settings that are global to the whole project. An easy way to put them already in the database is to regard them as properties of the root node (which has not a function right now other then a placeholder for all the experiment nodes). So all global settings should be stored via setProperty on the root node and (when needed) be retrieved from the root node. For convenience I can make a class for the preferences to do this.
