### ISSUE TITLE
Change database folder 

### ISSUE THREAD

**Issue by vcaldas** [vcaldas/iSBatch#30]
The database folder is now saved with a generic name. It should be NameOfTheDatabase_files, to avoid conflicts

**Comment by cmpunter** [comment]
In the constructor of the Root node the foldername of the database is specified:

```
public Root(String outputFolder) {
	super(null, type);
		
	outputFolder += File.separator + "database_files";
		
	if (!new File(outputFolder).exists())
		new File(outputFolder).mkdirs();
		
	setProperty("name", "Database");
	setProperty("outputFolder", outputFolder);
}
```

To accomplish this we need to set a name for the root node and then change the outputFolder name. I will look into this.

**Comment by cmpunter** [comment]
I changed the root node. Keep in mind that existing databases won't work now since the name of the database determines the name of the folder with the database files! There no other correspondence between the two.
