### ISSUE TITLE
.project in .gitignore ?

### ISSUE THREAD

**Issue by cmpunter** [vcaldas/iSBatch#35]
Currently I always get error messages since the configured Java builder is not working in my Eclipse. It might be that this is due to some paths that are set for the build path. We should consider removing the Java builder from the project configuration, then commit this to master and then add .project to the .gitignore file. This way we can all have our own build configurations without accidentally committing the build configuration to the master branch.

**Comment by vcaldas** [comment]
The errors is usually because the AntBuilder misses some configurations. Without the antbuilder, the full package won't be compiled properly since iSBatch depends on external libraries. We may indeed include that to the gitignore, but be aware of that issue.
